gesdinet_jwt_refresh_token:
  refresh_token_class: App\Entity\RefreshToken
  ttl: 2592000 #1 month
  ttl_update: true
  firewall: api_token_refresh
  token_parameter_name: refreshToken
  user_provider: 'security.db_user_provider'

